# Generated by Django 3.2.23 on 2023-12-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='designers_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=90)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Certificate', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='designs_tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('design', models.FileField(upload_to='')),
                ('discription', models.TextField()),
                ('DESIGNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.designers_table')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='manufacturer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=90)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('License', models.FileField(upload_to='')),
                ('Email', models.CharField(max_length=100)),
                ('Photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='materials_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='')),
                ('price', models.FloatField()),
                ('stock', models.BigIntegerField()),
                ('details', models.TextField()),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.manufacturer_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=90)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='tailorshop_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('License', models.FileField(upload_to='')),
                ('Email', models.CharField(max_length=100)),
                ('Photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='rating_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviews', models.TextField()),
                ('rating', models.FloatField()),
                ('Date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='orderinfo_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('DESIGNS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.designs_tables')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.materials_table')),
            ],
        ),
        migrations.AddField(
            model_name='designers_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.login_table'),
        ),
        migrations.CreateModel(
            name='custom_desgin_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('design_details', models.TextField()),
                ('DESIGNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.designers_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('Date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='assign_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('orderinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.orderinfo_table')),
                ('tailorshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royaloutfit.tailorshop_table')),
            ],
        ),
    ]
