# Generated by Django 3.2.20 on 2024-03-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaloutfit', '0003_moredesigntable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moredesigntable',
            name='design_more',
            field=models.FileField(upload_to=''),
        ),
    ]
