from django.urls import path

from royaloutfit import views

urlpatterns=[

    path('',views.login1,name='login1'),
    path('logout',views.logout,name='logout'),
    path('block',views.block,name='block'),
    path('Coordinator',views.Coordinator,name='Coordinator'),
    path('manufacture',views.manufacture,name='manufacuture'),

    path('Manufacture_signup', views.Manufacture_signup, name='Manufacture_signup'),
    path('registration',views.registration,name='registration'),
    path('sendreplay/<int:id>',views.sendreplay,name='sendreplay'),
    path('acceptmanufacture/<int:id>', views.acceptmanufacture, name='acceptmanufacture'),
    path('rejectmanufacture/<int:id>', views.rejectmanufacture, name='rejectmanufacture'),
    path('blockmanufacture/<int:id>', views.blockmanufacture, name='blockmanufacture'),
    path('unblockmanufacture/<int:id>', views.unblockmanufacture, name='unblockmanufacture'),
    path('searchmanufacture/<int:id>', views.searchmanufacture, name='searchmanufacture'),
    path('verifymanufacture',views.verifymanufacture,name='verifymanufacture'),
    path('searchrating',views.searchrating,name='searchrating'),
    path('block1',views.block1,name='block1'),
    path('add_reply',views.add_reply,name='add_reply'),
    path('searchmanufacture',views.searchmanufacture,name='searchmanufacture'),
    path('searchcomplaints', views.searchcomplaints, name='searchcomplaints'),
    path('viewcompailnts',views.viewcompailnts,name='viewcompailnts'),
    path('viewrateing',views.viewrateing,name='viewrateing'),
    path('adddesign',views.adddesign,name='adddesign'),
    path('editdesign/<int:id>',views.editdesign,name='editdesign'),
    path('deletedesign/<int:id>',views.deletedesign,name='deletedesign'),
    path('deletedesigners/<int:id>',views.deletedesigners,name='deletedesigners'),
    path('editdesigners/<int:id>',views.editdesigners,name='editdesigners'),
    path('edit_designers_post',views.edit_designers_post,name='edit_designers_post'),
    path('add_design_post', views.add_design_post, name='add_design_post'),

    path('add_designers_post', views.add_designers_post, name='add_designers_post'),

    path('add_design_post',views.add_design_post,name='add_design_post'),
    path('customisedesign',views.customisedesign,name='customisedesign'),
    path('designhome',views.designhome,name='designhome'),
    path('managedesign',views.managedesign,name='managedesign'),
    path('more_designs/<int:id>', views.more_designs,name='more_designs'),
    path('add_more_designs',views.add_more_designs,name='add_more_designs'),
    path('add_more_design_post',views.add_more_design_post,name='add_more_design_post'),
    path('adddesigners',views.adddesigners,name='adddesigners'),
    path('searchdesigners',views.searchdesigners,name='searchdesigners'),
    path('acceptdesign/<int:id>',views.acceptdesign,name='acceptdesign'),
    path('unblocktailorshop/<int:id>',views.unblocktailorshop,name='unblocktailorshop'),
    path('blocktailorshop/<int:id>',views.blocktailorshop,name='blocktailorshop'),
    path('rejectdesign/<int:id>',views.rejectdesign,name='rejectdesign'),
    path('addmaterial',views.addmaterial,name='addmaterial'),
    path('add_material_post', views.add_material_post, name='add_material_post'),
    path('edit_materials/<int:id>', views.edit_materials, name='edit_materials'),
    path('delete_materials/<int:id>', views.delete_materials, name='delete_materials'),
    path('edit_material_post', views.edit_material_post, name='edit_material_post'),
    path('searchmaterials', views.searchmaterials, name='searchmaterials'),
    path('searchtailorshop', views.searchtailorshop, name='searchtailorshop'),
    path('srch_block_unblocktrailorshop', views.srch_block_unblocktrailorshop, name='srch_block_unblocktrailorshop'),
    path('searchdesign', views.searchdesign, name='searchdesign'),
    path('searchcustomisedesign', views.searchcustomisedesign, name='searchcustomisedesign'),
    path('blockdesigners/<int:id>', views.blockdesigners, name='blockdesigners'),
    path('unblockdesigners/<int:id>', views.unblockdesigners, name='unblockdesigners'),
    path('searchdesigners', views.searchdesigners, name='searchdesigners'),
    path('searchvieworder', views.searchvieworder, name='searchvieworder'),
    path('searchmanagematerials', views.searchmanagematerials, name='searchmanagematerials'),

    path('addts',views.addts,name='addts'),
    path('assigntotrailorshop/<int:id>',views.assigntotrailorshop,name='assigntotrailorshop'),
    path('assigntlr',views.assigntlr,name='assigntlr'),
    path('Block_unblockdesigners',views.Block_unblockdesigners,name='Block_unblockdesigners'),
    path('block_unblocktrailorshop',views.block_unblocktrailorshop,name='block_unblocktrailorshop'),
    path('managematerials',views.managematerials,name='managematerials'),
    path('managetailorshop',views.managetailorshop,name='managetailorshop'),
    path('add_taliorshop_post',views.add_taliorshop_post,name='add_taliorshop_post'),
    path('edit_tailorshop/<int:id>', views.edit_tailorshop, name='edit_tailorshop'),
    path('edit_taliorshop_post', views.edit_taliorshop_post, name='edit_taliorshop_post'),
    path('delete_taliorshop/<int:id>', views.delete_taliorshop, name='delete_taliorshop'),
    path('delete_design/<int:id>', views.delete_design, name='delete_design'),




    path('manufacturehome',views.manufacturehome,name='manufacturehome'),
    path('searchtailorshop1',views.searchtailorshop1,name='searchtailorshop1'),
    path('manage_designers',views.manage_designers,name='manage_designers'),
    path('vieworderstatus',views.vieworderstatus,name='vieworderstatus'),
    path('searchvieworderstatus',views.searchvieworderstatus,name='searchvieworderstatus'),
    path('searchviewrating',views.searchviewrating,name='searchviewrating'),
    path('viewrating',views.viewrating,name='viewrating'),
    path('vieworder',views.vieworder,name='vieworder'),
    path('login_code',views.login_code,name='login_code'),
    path('edit_design_post',views.edit_design_post,name='edit_design_post'),
    path('chatwithuser', views.chatwithuser, name='chatwithuser'),
    path('chatview', views.chatview, name='chatview'),
    path('coun_msg/<int:id>', views.coun_msg, name='coun_msg'),
    path('coun_insert_chat/<str:msg>/<int:id>', views.coun_insert_chat, name='coun_insert_chat'),

    # ///////////////////////////////////// webservice //////////////////////////////

    path('login_code_and', views.login_code_and, name="login_code_and"),
    path('user_register', views.user_register, name="user_register"),
    path('send_complaint', views.send_complaint, name="send_complaint"),
    path('complaints_reply', views.complaints_reply, name="complaints_reply"),
    path('send_rating', views.send_rating, name="send_rating"),
    path('view_design', views.view_design, name="view_design"),
    path('view_materials', views.view_materials, name="view_materials"),
    path('view_tailors', views.view_tailors, name="view_tailors"),
    path('view_message2', views.view_message2, name="view_message2"),
    path('in_message2', views.in_message2, name="in_message2"),
    path('view_designers', views.view_designers, name="view_designers"),
    path('order', views.order, name="order"),
    path('view_assigned_work', views.view_assigned_work, name="view_assigned_work"),
    path('view_custom_design', views.view_custom_design, name="view_custom_design"),
    path('view_user', views.view_user, name="view_user"),
    path('update_status', views.update_status, name="update_status"),
    path('view_user_custom_design', views.view_user_custom_design, name="view_user_custom_design"),
    path('send_custom_design', views.send_custom_design, name="send_custom_design"),
    path('view_designers_drop', views.view_designers_drop, name="view_designers_drop"),
    path('view_more_design', views.view_more_design, name="view_more_design"),


]
